Algoritmo "entrada de dados padrão"

Var

   nome:caracter
   idade: inteiro
   S1:real
   S2:real

Inicio
  escreva("escreva seu nome: ")
  leia(nome)
  escreva("digite sua idade: ")
  leia(idade)
  escreval("escreva seus ultimos dois salarios: ")
  leia(S1)
  leia(S2)
  
  escreval("dados digitados ")
  escreval("nome: ", nome)
  escreval("idade: ", idade)
  escreval("S1 = ", S1:8:2)
  escreval("S2 = ", S2:8:2)

Fimalgoritmo